/**
 * This script extracts all courses from EWI from the TU Delft API.
 */

var https = require('https');
var url = require('url');
var db = require('./../db')
var removeDiacritics = require('diacritics').remove;

connection = db.connect();

var studieprogrammaboom;
var studieprogrammas = [];
var vakken = [];
var i = 0;
var a = 0;

/**
 * Construct proper formats and save the courses
 * to the database
 * @param data
 */
function saveCourseInformation(data) {
	if (data != null) {
		var course = {courseid: '', name: '', contents: '', studygoals: ''};
		course.courseid = data.vak.cursusid;
		course.name = removeDiacritics(data.vak.langenaamEN);

		var info = data.vak.extraUnsupportedInfo.vakUnsupportedInfoVelden;
		info.forEach(function (item) {
			if (item["@label"] == 'Course Contents') {
				course.contents = removeDiacritics(item.inhoud);
			}
			if (item["@label"] == 'Study Goals') {
				if (course.courseid == 'ET3000') {
					console.log(item.inhoud);
				}
				course.studygoals = removeDiacritics(item.inhoud);
			}
		});

		connection.safe_query("SELECT * FROM course WHERE courseid = '" + course.courseid + "'", function (rows, fields) {
			if (rows.length == 0) {
				connection.safe_query('INSERT INTO course SET ?', course, function (result) {
					if (err) console.log(err);
				});
			}
		});
	}
}

/**
 * Loops through all studies found by the TU Delft API
 * and find the course IDs of all studies
 * @param data (generated by 
 */
function extractCourseIds(data) {
	var opleidingen = data.getOpleidingenByFacultyAndYearResponse.opleiding;
	
	opleidingen.forEach(function(opleiding) {		
		studieprogrammaboom = opleiding.studieprogrammaboom;
		findStudieprogrammas(studieprogrammaboom);
	});

	findVakken(studieprogrammas);
	
	vakken.forEach(function(courseId) {
		callTuAPI("/vakken/" + courseId, saveCourseInformation);
	});
}

/**
 * Given a studieprogrammaboom, find all underlying
 * studieprogrammas and save them in the studieprogrammas array
 * @param studieprogrammaboom
 */
function findStudieprogrammas(studieprogrammaboom) {
	if (studieprogrammaboom != null) {
		if (Array.isArray(studieprogrammaboom.studieprogramma)) {
			studieprogrammaboom.studieprogramma.forEach(function(studieprogramma) {
				studieprogrammas[a] = studieprogramma;
				a++;
				if (studieprogramma.studieprogrammaboom != null) {
					findStudieprogrammas(studieprogramma.studieprogrammaboom);
				}
			});
		}
		else {
			studieprogrammas[a] = studieprogrammaboom;
			a++;
			if (studieprogrammaboom.studieprogrammaboom != null) {
				findStudieprogrammas(studieprogrammaboom.studieprogrammaboom);
			}
		}
	}
}

/**
 * Given an array of studieprogrammas from the TU Delft API
 * search for all courses in these studieprogrammas
 * @param studieprogrammas
 */
function findVakken(studieprogrammas) {
	studieprogrammas.forEach(function(studieprogramma) {
		if (studieprogramma.vak != null) {
			if (Array.isArray(studieprogramma.vak)) {
				studieprogramma.vak.forEach(function(vak) {
					vakken[i] = vak.kortenaamNL;
					i++;
				});
			}
			else {
				vakken[i] = studieprogramma.vak.kortenaamNL;
				i++;
			}
		}
	});
}

/**
 * Generates a call to the API of the TU Delft
 * and returns the buffer as an argument to the callback
 * @param api_url_specific
 * @param callback
 */
function callTuAPI(spec_path, callback) {
	var hostname = "api.tudelft.nl";
	var base_path = "/v0";

	var buffer = "";
	console.log("Request to TU Delft API with URL: " + hostname+base_path+spec_path);
	var request = https.get({hostname: hostname,
		path: base_path+spec_path,
			keepAlive: true}, function (response) {
		response.on("data", function (chunk) {
		    buffer += chunk;
		});
		
		response.on("end", function (err) {
			try {
				buffer = JSON.parse(buffer);
				callback(buffer);
			}
			catch(err) {
				console.log(err);
			}
		}); 
	}).on('error', function(e) {
	  console.error('error jaaa'+e);
	});
}

callTuAPI("/opleidingen/EWI?studiejaarid=10", extractCourseIds);